skift-org/skift

ReadMe.md
Mostly just a few tiny spelling errors, and grammar adjustments here and there.
=> Fix typos in ReadMe.md

kernel/multiboot/Multiboot.c, manual/building.md
Commands are added that allow obtaining the code from third-party libraries and thus avoid compilation failures when building the kernel
=> update the file building.md

arch/x86/boot.s
reeeeally small fix to a comment.
=> bootstrap: comment fix.

applications/task-manager/main.cpp
=> Display percentage of RAM and CPU in task manager

kernel/filesystem/Filesystem.cpp, kernel/filesystem/Filesystem.h, kernel/modules/Ramdisk.cpp, libraries/libfile/tar.cpp, libraries/libfile/tar.h
Note: this currently works for files only because filesystem_mklink doesn't create links for directories
=> Ramdisk: Add ability to add links in tar

coreutils/man.cpp, kernel/.build.mk, libraries/libsystem/core/CString.h, libraries/libsystem/core/Plugs.h, libraries/libsystem/io/Path.cpp, libraries/libsystem/io/Path.h, sysroot/System/Manuals/man.json
=> [NEW] Add --list option to man

applications/settings/settings.markup, applications/widget-factory/main.cpp, libraries/libwidget/dialog/MessageBox.cpp
=> Fix some alignment problems

Makefile
Fixes #77 qemu bricking the terminal
**Note**: this is my first attempt at using git to a manage pull request
=> Replace mon:stdio with stdio

libraries/libc/ctype.h
=> build system: fix ctype.h

applications/paint/PaintTool.cpp, libraries/libsystem/math/Bresenham.h
Don't merge it yet. The brush line often stops rendering out of nowhere
=> paint: implement another brush engine

libraries/libwidget/Event.h, libraries/libwidget/Window.cpp, libraries/libwidget/Window.h
WINDOW_RESIZED is triggered when the user resizes the window
WINDOW_SIZE_CHANGED is like WINDOW_RESIZED but it can be triggered when the window->size() method is called
=> libwidget: added WINDOW_RESIZE event

kernel/memory/Virtual.cpp
=> Meta: Fixing coding style

applications/coreutils/.build.mk, applications/coreutils/sysfetch.cpp, applications/coreutils/uname.cpp, kernel/tasking/Syscalls.cpp, libraries/abi/System.h
I think I did everything correctly :sweat_smile: (Feel free to correct me if I'm wrong)
=> Added a new command: Uname + edit some field of systeminfo 

applications/coreutils/.build.mk, applications/coreutils/false.cpp, applications/coreutils/true.cpp, applications/coreutils/yes.cpp
It's possible that the build fail, if so we'll need to modify `applications/coreutils/.build.mk`
Those additions are according to the issue #162
=> Coreutils: added true, false and yes

libraries/libsystem/cmdline/CMDLine.cpp
Here is a little screenshot of the fix
=> CommandLineOption: Fix aligment on options (Issue #161)

applications/calculator/calculator.markup, applications/calculator/main.cpp
for the moment there is 'only' 5 operator : 
add (+)
substract (-)
equal (=)
clear (c)
clear all (ce)﻿
=> calculator: added basic calculator operator and now it just work

applications/coreutils/.build.mk, applications/coreutils/cp.cpp
created basic cp command in coreutils. It uses read and write stream to copy contents of one file to another (that is newly created).
=> Coreutils : created basic cp command

applications/menu/main.cpp
when you click on the bottom menu button, now it launch programm ! 
file button launch file programm 
setting button launch setting programm
=> menu: now menu button (file + setting) work

applications/coreutils/.build.mk, applications/coreutils/rmdir.cpp, libraries/libsystem/Result.cpp, libraries/libsystem/Result.h, libraries/libsystem/io/Filesystem.h
Implemented rmdir, added descriptions to libraires/libsystem/Result.h. 
Tell me if I have to make any changes 😄 
Also, thankyou @sleepy-monax for helping me throughout :)
=> coreutils: implemented rmdir

coding_style.md
We forgot the rule with the curly braces and `nullptr` :sweat_smile:
=> Coding Style: Added a forgotten rule

applications/coreutils/.build.mk, applications/coreutils/basename.cpp
Implemented basename coreutil.
=> coreutils: basename command added

applications/coreutils/.build.mk, applications/coreutils/head.cpp
#162: Add head command 
Head command displays the first ten lines of the FILE by default
**NOTE:**
- ~~Reading input from STDIN is broken at the moment~~
- Negative count values yet to be supported
=> coreutils: head command

applications/calculator/Calculator.h, applications/calculator/calculator.markup, applications/calculator/main.cpp
Added 1/x, exp and sqrt operations for the calculator!
=> calculator: reciprocal, exp and sqrt operations added

architectures/x86_64/kernel/GDT.cpp, architectures/x86_64/kernel/GDT.h, architectures/x86_64/kernel/Interrupts.h, architectures/x86_64/kernel/helper.s
there is a lot of fix with the gdt
=> long mode interrupt work ! :tada:

applications/coreutils/.build.mk, applications/coreutils/play.cpp, kernel/devices/DeviceClass.h, kernel/devices/Driver.cpp, kernel/devices/PCIDevice.h, kernel/drivers/AC97.cpp, kernel/drivers/AC97.h, makefile
Added the AC97 Sound Device and a simple Play utility to play music ( wave file 44.1khz ). I'll try to add volume control and sample rate control next :smile:
=> AC97 : Created Sound Device 

toolbox/convert-audio.sh
It's just a small script. We should write a proper WAV decoder in the future
=> sound: Add script to convert audio files

applications/coreutils/.build.mk, applications/coreutils/piano.cpp, kernel/bus/Legacy.cpp, kernel/bus/LegacyAddress.h, kernel/devices/DeviceClass.h, kernel/devices/Driver.cpp, kernel/devices/LegacyDevice.h, kernel/drivers/PCSpeaker.cpp, kernel/drivers/PCSpeaker.h, makefile
added driver for the PC speaker device and wrote a simple piano utility that can read files containing notes and play them using the PC speaker device. :smiley_cat:
=> pcspeaker & piano: created pcspeaker device driver and piano utility

applications/nyancat/nyancat.cpp
I've replaced `NULL` with `nullptr`.
=> Replaced NULL with nullptr

kernel/bus/PCI.cpp
I've added braces to some `if` statements that didn't have them.
=> Fixed coding style

libraries/libutils/String.h
I added a sub-string function for getting segments of strings.
`String::substr(start, length)`
=> Added substr function

applications/task-manager/RAMGraph.h, applications/task-manager/manifest.json
I fixed some grammatical errors in the task manager
=> task-manager: Fixed grammatical errors

manual/contributing.md
fixed 2 typo's in manual/contributing.md
=> fix typo's

apps/onboarding/main.cpp
right => next page
left => previous page
escape => quit application
=> onboarding: added keyboard shortcuts

manual/building.md
updated contributing.md link from https://github.com/skiftOS/skift/blob/main/manual/manual/contributing.md to https://github.com/skiftOS/skift/blob/main/manual/contributing.md
=> update contributing.md link

apps/.build.mk, apps/utilities/.build.mk, configs/debug.mk, configs/defaults.mk, configs/develop.mk, configs/release.mk, makefile
Reduces overall image size by ~8MB in my tests
=> meta: strip executable binaries

apps/utilities/unzip.cpp, libraries/libfile/ZipArchive.cpp, libraries/libfile/ZipArchive.h, libraries/libsystem/compression/Deflate.cpp, libraries/libsystem/compression/Deflate.h, libraries/libsystem/compression/DeflateReader.cpp, libraries/libsystem/compression/DeflateReader.h, libraries/libsystem/compression/DeflateWriter.cpp, libraries/libsystem/compression/DeflateWriter.h, libraries/libsystem/compression/Huffman.h, libraries/libsystem/compression/Inflate.cpp, libraries/libsystem/compression/Inflate.h, libraries/libsystem/io/BinaryReader.cpp, libraries/libsystem/io/BinaryReader.h, libraries/libsystem/io/BinaryWriter.h, libraries/libsystem/io/BitReader.h, libraries/libsystem/io/BitWriter.h, libraries/libsystem/io/FileReader.h, libraries/libsystem/io/FileWriter.h, libraries/libsystem/io/MemoryReader.cpp, libraries/libsystem/io/MemoryReader.h, libraries/libsystem/io/MemoryWriter.cpp, libraries/libsystem/io/MemoryWriter.h, libraries/libsystem/io/Reader.h, libraries/libsystem/io/ScopedReader.cpp, libraries/libsystem/io/ScopedReader.h, libraries/libsystem/io/Writer.cpp
=> libsystem: Extend stream api

manual/10-utilities/displayctl.md, manual/10-utilities/wallpaperctl.md
I redid the pr to minimize the amount of commit in the pr, and to name the commit correctly.
=> Manual: Fix small error in some pages of the manual.

apps/utilities/cat.cpp, kernel/drivers/LegacyATA.cpp, kernel/drivers/LegacyATA.h, kernel/drivers/LegacyMouse.h, libraries/libsystem/io/Writer.cpp, libraries/libutils/Array.h, libraries/libutils/Vector.h
Add an array class similar to `Vector<T>`. Allows us to do additional error checking and have a common interface for algorithms that might come in the future ( similar to STL ). Use it in some places, but probably not everywhere yet
=> Array class

libraries/libsystem/Time.cpp
Would compute the wrong date before and potentially crash in december (out of bounds)
=> libsystem: Fix date computation

userspace/libraries/libio/Copy.h, userspace/libraries/libio/Format.h, userspace/libraries/libmath/Vec2.h, userspace/libraries/libmath/Vec3.h, userspace/libraries/libutils/ArgParse.h, userspace/utilities/basename.cpp, userspace/utilities/cat.cpp, userspace/utilities/crc32.cpp, userspace/utilities/dirname.cpp, userspace/utilities/displayctl.cpp, userspace/utilities/head.cpp, userspace/utilities/json.cpp, userspace/utilities/keyboardctl.cpp, userspace/utilities/kill.cpp, userspace/utilities/ls.cpp, userspace/utilities/mkdir.cpp, userspace/utilities/now.cpp, userspace/utilities/powerctl.cpp, userspace/utilities/rmdir.cpp, userspace/utilities/settingsctl.cpp, userspace/utilities/tac.cpp, userspace/utilities/uname.cpp, userspace/utilities/unzip.cpp, userspace/utilities/zip.cpp
=> apps: rework utiltiies

sysroot/Files/Tests/xml/basic.xml, sysroot/Files/Tests/xml/empty_tags.xml, userspace/libraries/libio/Scanner.h, userspace/libraries/libxml/.build.mk, userspace/libraries/libxml/Declaration.h, userspace/libraries/libxml/Document.h, userspace/libraries/libxml/Node.h, userspace/libraries/libxml/Parser.cpp, userspace/libraries/libxml/Parser.h, userspace/tests/.build.mk, userspace/tests/libxml/BasicTest.cpp, userspace/tests/libxml/SvgTest.cpp
=> libxml: start working on an xml parser

readme.md
The article should be determined by the noun ("terminal") not the adjective ("UNIX-like")
=> Fix article

readme.md
- Changed "created from scratch" to "built from scratch"
- Changed "C/C++" to "C and C++"
- Changed "for ARM, x86, and RISC-V platforms" to "for ARM, x86, and RISC-V architectures"
=> Made some changes to the "about" part of README.md

readme.md
I don't think "contributings" is a word. Please correct me if I'm wrong.
=> Improve grammar

meta/plugins/start/runner.py
In building.md, under the build and run section it says:
> [!NOTE]
> Running this step requires being in a graphical environment with a build of QEMU supporting graphics either via SDL or GTK. If you are using a headless server, you can use the `./skift.sh image build --format=hdd` command to build a disk image.
However a qemu without SDL would result in
```
qemu-system-x86_64: Display 'sdl' is not available.
```
So I fixed that. Also I thought it would be a good idea to swap -mon:stdio with `-chardev stdio,id=char0,signal=on -serial chardev:char0` for compatibility with escape signals (eg. Ctrl+C). I'm not sure if this is what you want but I can undo if necessary.
=> Change qemu setup to support GTK and allow Ctrl+C quit

doc/building.md
The old check was last run 9 months ago and is inaccurate of the current build status i switched the checks to the new checks
Also i like your project (:
=> Docs - Building | Updated the checks badges
